name: Continuous Integration

on:
  push:

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Run lint
        run: |
          yarn lint
      - name: Run css lint
        run: |
          yarn lint:css
      - name: Run tests and check coverage
        env:
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
          REACT_APP_RIBON_API: ${{ secrets.REACT_APP_RIBON_API }}
          REACT_APP_URL_SIGNATURE_KEY: ${{ secrets.REACT_APP_URL_SIGNATURE_KEY }}
        run: |
          yarn testCoverage
